/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static void main(String[] args) {
        NIOServer server =  new NIOServer(1932);
        server.listen();
    }
}
