package net.iapploft;

import net.iapploft.proxy.RpcClientProxy;
import net.iapploft.service.DWService;
import net.iapploft.registry.ZKServiceDiscovery;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ClientApp {


    public static void main(String[] args) {
        //发现服务
        ZKServiceDiscovery zkServiceDiscovery = new ZKServiceDiscovery();

        RpcClientProxy proxy = new RpcClientProxy(zkServiceDiscovery);
        DWService dwService = proxy.create(DWService.class);
        for (int i=0;i<100;i++)
        {
            System.out.println(dwService.hello("dave wang"));
        }


    }
}
