package net.iapploft;

import net.iapploft.annotation.RpcService;
import net.iapploft.bean.RpcServer;
import net.iapploft.service.DWService;
import net.iapploft.service.DWServiceImpl;
import net.iapploft.service.ServiceRegistryCenter;
import net.iapploft.service.ZKServiceRegistryCenterImpl;

import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ServerApp {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {

        DWService dwService = new DWServiceImpl();
        //1.服务注册  服务名：dwService  服务地址 127.0.0.1:8080
        ServiceRegistryCenter center = new ZKServiceRegistryCenterImpl();
        RpcServer rpcServer = new RpcServer(center,"127.0.0.1:8080");
        //2.netty监听网络上过来的对象
        rpcServer.bind(dwService);
        rpcServer.registerAndListen();

        //BIO  1.每个客户端都会开启线程 2.连接结束线程结束



    }
}
